version: '3.4'

services:

  pg:
    image: postgres
    container_name: postgres
    command: postgres -c 'max_connections=400'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cinema_db
    ports:
      - "5433:5432"
    networks:
      - backendnetwork


networks:
  backendnetwork:
    driver: bridge
