version: '3.4'

services:

  pg:
    image: postgres
    container_name: postgres
    command: postgres -c 'max_connections=400'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cinema_db
    ports:
      - "5433:5432"
    networks:
      - backendnetwork

  test-task:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: test-task-bknd
    ports:
      - 8075:8075
      - 18075:18075
    depends_on:
        - pg
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - backendnetwork


networks:
  backendnetwork:
    driver: bridge
