version: '3.4'

services:

  cheddar-bknd:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: cheddar-bknd
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - backendnetwork

networks:
  backendnetwork:
    driver: bridge
